version: 0.2
env:
  shell: bash
phases:
  install:
    commands:
    - pip install -r requirements.txt
  pre_build:
    commands:
    - git clone https://github.com/ahmsay/Solidvessel.git
  build:
    commands:
    - python extract_docs.py